server:
  port: 9527
spring:
  application:
    name: ZUUL-GATEWAY #这里Spring。application。name必须大写哦！！！
eureka:
  client:
    service-url:
       defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527 #显示的名字而已
    prefer-ip-address: true
zuul:   #这里定义映射规则
  routes:
    hy.serviceId: EMPLOYEE-PROVIDER
    hy.path: /hy/**
  ignored-services: user-provider  #user-provider #(此处需要小写！！)忽略直接使用服务名访问  *忽略所有的
  prefix: "/yimai"  #配置前缀。
